export const FOLDER_STATES = {
  PRE: 'Anuncio Previo',
  PUB: 'En plazo',
  EV: 'Pendiente de adjudicacion',
  ADJ: 'Adjudicada',
  RES: 'Resuelta',
  ANUL: 'Anulada'
}

export const CONTRACT_TYPES = {
  1: 'Suministros',
  2: 'Servicios',
  3: 'Obras',
  21: 'Gestión de Servicios Públicos',
  31: 'Concesión de Servicios Públicos',
  40: 'Colaboración entre el sector público y sector privado',
  7: 'Administrativo especial',
  8: 'Privado',
  50: 'Patrimonial',
  999: 'Otros'
}

export const CONTRACT_SUBTYPES = {
  Servicios: {
    1: 'Servicios de mantenimiento y reparación',
    2: 'Servicios de transporte por vía terrestre, incluidos los servicios de furgones blindados y servicios de mensajería, excepto el transporte de correo',
    3: 'Servicios de transporte aéreo: transporte de pasajeros y carga, excepto el transporte de correo',
    4: 'Transporte de correo por vía terrestre y por vía aérea',
    5: 'Servicios de telecomunicación',
    6: 'Servicios financieros: a) servicios de seguros; b) servicios bancarios y de inversión',
    7: 'Servicios de informítica y servicios conexos',
    8: 'Servicios de investigación y desarrollo',
    9: 'Servicios de contabilidad, auditoría y teneduría de libros',
    10: 'Servicios de investigación de estudios y encuestas de la opinión pública',
    11: 'Servicios de consultores de dirección y servicios conexos',
    12: 'Servicios de arquitectura; servicios de ingeniería y servicios integrados de ingeniería; servicios de planificación urbana y servicios de arquitectura paisajista. Servicios conexos de consultores en ciencia y tecnología. Servicios de ensayos y anílisis tícnicos',
    13: 'Servicios de publicidad',
    14: 'Servicios de limpieza de edificios y servicios de administración de bienes raíces',
    15: 'Servicios editoriales y de imprenta, por tarifa o por contrato',
    16: 'Servicios de alcantarillado y eliminación de desperdicios: servicios de saneamiento y servicios similares',
    17: 'Servicios de hostelería y restaurante',
    18: 'Servicios de transporte por ferrocarril',
    19: 'Servicios de transporte fluvial y marítimo',
    20: 'Servicios de transporte complementarios y auxiliares',
    21: 'Servicios jurídicos',
    22: 'Servicios de colocación y suministro de personal',
    23: 'Servicios de investigación y seguridad, excepto los servicios de furgones blindados',
    24: 'Servicios de educación y formación profesional',
    25: 'Servicios sociales y de salud',
    26: 'Servicios de esparcimiento, culturales y deportivos',
    27: 'Otros servicios',
  },
  Patrimonial: {
    10: 'Autorización demanial',
    11: 'Concesión demanial',
    20: 'Explotación de bienes inmuebles mediante arrendamiento',
    21: 'Explotación de bienes muebles mediante arrendamiento',
    22: 'Explotación de bienes de propiedad incorporal',
    23: 'Cesión de uso/titularidad',
    30: 'Adquisición de inmuebles',
    31: 'Adquisición de derechos de propiedad incorporal',
    40: 'Arrendamiento de inmuebles',
    50: 'Enajenación de inmuebles',
    51: 'Enajenación de bienes muebles',
    52: 'Enajenación de derechos de propiedad incorporal',
    60: 'Permuta',
    100: 'Otros contratos patrimoniales',
  },
  Suministros: {
    1: 'Alquiler',
    2: 'Adquisición',
  },
  Obras: {
    4500: 'Construcción',
    4510: 'Preparación de obras',
    4511: 'Demolición de inmuebles y movimientos de tierras',
    4512: 'Perforaciones y sondeos',
    4520: 'Construcción general de inmuebles y obras de ingeniería civil',
    4521: 'Construcción general de edificios y obras singulares de ingeniería civil (puentes, túneles, etc.)',
    4522: 'Construcción de cubiertas y estructuras de cerramiento',
    4523: 'Construcción de autopistas,carreteras, campos de aterrizaje, vías férreas y centros deportivos',
    4524: 'Obras hidráulicas',
    4525: 'Otras construcciones especializadas',
    4530: 'Instalación de edificios y obras',
    4531: 'Instalación eléctrica',
    4532: 'Aislamiento térmico, acústico y antivibratorio',
    4533: 'Fontanería',
    4534: 'Otras instalaciones de edificios y obras',
    4540: 'Acabado de edificios y obras',
    4541: 'Revocamiento',
    4542: 'Instalaciones de carpintería',
    4543: 'Revestimiento de suelos y paredes',
    4544: 'Pintura y acristalamiento',
    4545: 'Otros acabados de edificios y obras',
    4550: 'Alquiler de equipo de construcción o demolición con operario',
  },
  "Colaboración entre el sector público y sector privado": {
    1: 'Suministros',
    2: 'Servicios',
    3: 'Obras',
  }
}

export const PROCESS_CODES = {
  1: 'Abierto',
  2: 'Restringido',
  3: 'Negociado sin publicidad',
  4: 'Negociado con publicidad',
  5: 'Diálogo competitivo',
  6: 'Contrato Menor',
  7: 'Derivado de acuerdo marco',
  8: 'Concurso de proyectos',
  100: 'Normas internas',
  999: 'Otros',
}

export const URGENCY_CODES = {
  1: 'Ordinaria',
  2: 'Urgente',
  3: 'Emergencia',
}

export const NUTS_CODES = {
  ES: 'España',
  ES1: 'Noroeste',
  ES11: 'Galicia',
  ES111: 'A Coruña',
  ES112: 'Lugo',
  ES113: 'Ourense',
  ES114: 'Pontevedra',
  ES12: 'Principado de Asturias',
  ES120: 'Asturias',
  ES13: 'Cantabria',
  ES130: 'Cantabria',
  ES2: 'Noreste',
  ES21: 'País Vasco',
  ES211: 'Araba',
  ES212: 'Gipuzkoa',
  ES213: 'Bizkaia',
  ES22: 'Navarra',
  ES220: 'Navarra',
  ES23: 'La Rioja',
  ES230: 'La Rioja',
  ES24: 'Aragón',
  ES241: 'Huesca',
  ES242: 'Teruel',
  ES243: 'Zaragoza',
  ES3: 'Comunidad de Madrid',
  ES30: 'Madrid',
  ES300: 'Madrid',
  ES4: 'Centro',
  ES41: 'Castilla y León',
  ES411: 'Ávila',
  ES412: 'Burgos',
  ES413: 'León',
  ES414: 'Palencia',
  ES415: 'Salamanca',
  ES416: 'Segovia',
  ES417: 'Soria',
  ES418: 'Valladolid',
  ES419: 'Zamora',
  ES42: 'Castilla-La Mancha',
  ES421: 'Albacete',
  ES422: 'Ciudad Real',
  ES423: 'Cuenca',
  ES424: 'Guadalajara',
  ES425: 'Toledo',
  ES43: 'Exremadura',
  ES431: 'Badajoz',
  ES432: 'Cáceres',
  ES5: 'Este',
  ES51: 'Cataluña',
  ES511: 'Barcelona',
  ES512: 'Girona',
  ES513: 'Lleida',
  ES514: 'Tarragona',
  ES52: 'Comunidad Valenciana',
  ES521: 'Alicante',
  ES522: 'Castelló',
  ES523: 'Valencia',
  ES53: 'Islas Baleares',
  ES531: 'Ibiza y formentera',
  ES532: 'Mallorca',
  ES533: 'Menorca',
  ES6: 'Sur',
  ES61: 'Andalucía',
  ES611: 'Almería',
  ES612: 'Cádiz',
  ES613: 'Córdoba',
  ES614: 'Granada',
  ES615: 'Huelva',
  ES616: 'Jaén',
  ES617: 'Málaga',
  ES618: 'Sevilla',
  ES62: 'Región de Murcia',
  ES620: 'Murcia',
  ES63: 'Ceuta',
  ES630: 'Ceuta',
  ES64: 'Melilla',
  ES640: 'Melilla',
  ES7: 'Canarias',
  ES70: 'Islas Canarias',
  ES701: 'Las Palmas',
  ES702: 'Tenerife',
  ES703: 'El Hierro',
  ES704: 'Fuerteventura',
  ES705: 'Gran Canaria',
  ES706: 'La Gomera',
  ES707: 'La Palma',
  ES708: 'Lanzarote',
  ES709: 'Tenerife',
}
